# Get R include and library paths
rlib := $(shell Rscript -e "R.home('lib')" | sed 's/\[1\] //g')
rinc := $(shell Rscript -e "R.home('include')" | sed 's/\[1\] //g')

all: mbg_tmb_model.so

mbg_tmb_model.so: mbg_tmb_model.cpp
	Rscript -e "TMB::compile('mbg_tmb_model.cpp', '-O1 -g',DLLFLAGS='')"

clean:
	rm -rf *dll
