#' @title Deduplicate linked cell preds
#'
#' @description Collapse rows of cell preds with multiple admin units in one pixel back into
#' single rows
#'
#' @param linked_cell_pred a cell pred merged to a link table generated by `get_link_table()`
#' @param overs a vector of the column names in the cell pred corresponding to draws
#' (typically V1:Vndraws)
#'
#' @return a cell pred object in original matrix form which corresponds to simple raster
#'
#' @export
dedupe_linked_cell_pred <- function(linked_cell_pred, overs) {

  # sum deaths for each duplicated pixel
  dedup_dt <- linked_cell_pred[, lapply(.SD, sum), by = cell_pred_id, .SDcols = overs]

  # reorder on cell_pred_id to match original order
  dedup_dt$cell_pred_id <- as.numeric(as.character(dedup_dt$cell_pred_id))
  setorder(dedup_dt, cell_pred_id)

  # drop columns and convert back into matrix
  deduped_linked_cell_pred <- dedup_dt[, overs, with = FALSE]
  deduped_linked_cell_pred <- as.matrix(deduped_linked_cell_pred)
  colnames(deduped_linked_cell_pred) <- NULL
  return(deduped_linked_cell_pred)
}
