#' @title Save Standard Covariate
#' @description Save an mbg output as a standard covariate
#'
#' @param cov_name Name for the covariate (how will it be called in the
#'                 fixed effects parameter?).  In most cases will be the same
#'                 as indicator.
#' @param ig Indicator groups
#' @param run_date Run date to pull from to make this covariate
#' @param ind Indicator (if different from cov name).  If `indicator` is NULL,
#'            (default) then `indicator` is set to `cov_name`.
#' @param raked Do you want to use the raked version?
#' @param year_list Vector (numeric) of years, with length the same as the number
#'                  of layers in your modeled output .tif
#' @param measure Covariate measure (e.g. mean, median, etc.)
#' @return Creates a series of .tif files, one for each year, in the standard MBG
#'         covariate directory using appropriate naming convention.  Note that for
#'         consistency with other covariates, these are expanded to global rasters.
#'         Also saves a readme.txt file with details of the covariate creation.
#' @examples
#' \dontrun{
#' save_standard_covariate(
#'   cov_name = "dpt3_cov_test",
#'   ig = "vaccine",
#'   run_date = "2017_10_27_12_55_26",
#'   raked = T,
#'   year_list = c(2000:2015),
#'   measure = "mean"
#' )
#' }
#' @export
save_standard_covariate <- function(cov_name,
                                    ig = indicator_group,
                                    run_date,
                                    ind = NULL,
                                    raked = T,
                                    year_list = c(2000:2015),
                                    measure = "mean") {

  # CONFIG ------------------------------------------------------------------
  # runtime configuration for central cluster
  if (Sys.info()["sysname"] == "Linux") {
    j_root <- "/home/j/"
  } else {
    stop("Run this on the cluster, please.")
  }

  if (is.null(ind)) ind <- cov_name

  # Set up directories
  std_cov_dir <- "/snfs1/WORK/11_geospatial/01_covariates/00_MBG_STANDARD/"
  sharedir <- paste0("/share/geospatial/mbg/", ig, "/", ind, "/output/", run_date, "/")

  # Load a global template
  template_file <- paste0(std_cov_dir, "worldpop/total/1y/worldpop_total_1y_2015_00_00.tif")
  template <- raster(template_file)

  # Read in raster files & format -------------------------------------------

  # Read in the covariate raster, trying different naming conventions
  if (raked == T) {
    raster_file <- paste0(sharedir, ind, "_", measure, "_raked_raster.tif")
  } else if (raked == F) {
    raster_file_1 <- paste0(sharedir, ind, "_", measure, "_raster.tif")
    raster_file_2 <- paste0(sharedir, ind, "_", measure, "_unraked_raster.tif")
    if (file.exists(raster_file_1)) {
      raster_file <- raster_file_1
    } else if (file.exists(raster_file_2)) {
      raster_file <- raster_file_2
    }
  }

  message("Loading raster file:")
  message(raster_file)
  r_brick <- brick(raster_file)

  if (length(year_list) != nlayers(r_brick)) {
    stop("Your year list does not match the number of layers in the raster brick.")
  }

  # Extend to global (using template)
  r_brick <- extend(r_brick, y = template, value = NA)

  # Write output files ------------------------------------------------------
  message("\n Writing covariate ", cov_name)

  ## Make dirs
  main_dir <- "/snfs1/WORK/11_geospatial/01_covariates/00_MBG_STANDARD/"
  out_dir <- paste0(main_dir, cov_name, "/", measure, "/1y/")
  dir.create(out_dir, recursive = T, showWarnings = F)

  ## Write raster layer for each year, raked and unraked
  for (i in 1:length(names(r_brick))) {
    subset_r_brick <- r_brick[[i]]
    year <- year_list[i]
    message(paste0("  Saving ", year))
    writeRaster(subset_r_brick,
      filename = paste0(out_dir, cov_name, "_", measure, "_1y_", year, "_00_00.tif"),
      format = "GTiff",
      overwrite = TRUE
    )
  }

  message("\nAll layers successfully saved in /snfs1/WORK/11_geospatial/01_covariates/00_MBG_STANDARD/")
  message(paste0("Covariate ", cov_name, " with measure ", measure, " ready to call in MBG config files in the fixed_effects parameter."))

  # Save a readme file -----------------------------------------------------
  readme_file <- paste0(out_dir, "readme.txt")
  fileConn <- file(readme_file)
  writeLines(
    c(
      "## MBG COVARIATE README #############################",
      "",
      paste0("Covariate generated by ", Sys.info()["user"], " on ", Sys.time(), "."),
      "",
      paste0("Covariate name: ", cov_name),
      "",
      "Details of MBG run used to produce this covariate:",
      paste0("  Indicator name: ", ind),
      paste0("  Indicator group: ", ig),
      paste0("  Run date: ", run_date),
      paste0("  Raked: ", raked),
      "",
      "####################################################"
    ),
    fileConn
  )
  close(fileConn)
}
